### ISSUE TITLE
Fix: Snowflake column selection

### ISSUE THREAD

**Issue by eogilvy12** [dbt-labs/dbt-codegen#11]
when running on Snowflake, if the schema and table name are lowercase, the generate base model returns the structure but without returning the column names.

If you update the schema to be capitalized an the table to have capitalized `identifier` then it works as expected

**Comment by clrcrl** [comment]
Thanks @eogilvy12.

Out of interest, what are your `quoting` configs in your Snowflake project? I'm trying to figure out why the test passed, but IRL is doesn't work.

Either way, I should probably be throwing an error when dbt can't find any columns, rather than letting it silently fail.

**Comment by eogilvy12** [comment]
up until this morning this project didn't have any quoting configs specified (! which I just changed)

I have to wait to merge some code in but can test this for you on whether it works with proper configuration

**Comment by eogilvy12** [comment]
@clrcrl once I added proper quoting to their dbt_project.yml the run-operation returns results!
