### ISSUE TITLE
Names are automatically casted to lower-case, regardless of capitalisation in database

### ISSUE THREAD

**Issue by JoshuaClercx** [dbt-labs/dbt-codegen#112]
### Describe the bug
Source, schema, database, table, and column names are automatically casted to lowercase when generating source yaml files, regardless of the casing of the name in the actual database.

### Steps to reproduce
Generate a source yaml file from any database that contains capitalisation in the names of any of the aforementioned.

### Expected results
Conservation of capitalisation in the yaml file as it is in the database.

### Actual results
All-lowercase names.

### Are you interested in contributing the fix?
Yes, as it would just require minor adjustments of a few lines.

**Comment by charmiraval** [comment]
This will be really helpful in case of different standards for ColumnName as per project instead of converting to lowercase.

**Comment by yuhouzhou** [comment]
Using the `persist_docs` configuration to sync the documentation between BigQuery and dbt docs requires matching cases of column names. It makes sense to have the option to keep the original case as in the databases.
