### ISSUE TITLE
macro 'dbt_macro__generate_model_yaml' takes no keyword argument 'model_names'

### ISSUE THREAD

**Issue by mbkupfer** [dbt-labs/dbt-codegen#126]
### Describe the bug

Compiling the generate model snippet returns a compilation error complaining about the keyword argument
```
Exception: Compilation Error in sql operation t_809e3c600c9943bab9708cc085afd1ea (from remote system.sql)
  macro 'dbt_macro__generate_model_yaml' takes no keyword argument 'model_names'

Detailed error information:
Error: Traceback (most recent call last):
  File "C:\Users\me\Anaconda3\envs\py38\lib\site-packages\dbt\clients\jinja.py", line 302, in exception_handler
    yield
  File "C:\Users\me\Anaconda3\envs\py38\lib\site-packages\dbt\clients\jinja.py", line 257, in call_macro
    return macro(*args, **kwargs)
  File "C:\Users\me\Anaconda3\envs\py38\lib\site-packages\jinja2\runtime.py", line 752, in __call__
    raise TypeError(
TypeError: macro 'dbt_macro__generate_model_yaml' takes no keyword argument 'model_names'
```

I even looked into at that macro in the dbt__packages folder and it looks like that macro does indeed take that argument.

### Steps to reproduce

Not sure how to reproduce.

### Expected results

No compilation error.

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/dbt_utils
    version: 0.8.5
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5
  - package: get-select/dbt_snowflake_monitoring
    version: 4.1.1
  - package: calogica/dbt_expectations
    version: 0.8.5
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.0
  - latest:    1.5.0 - Up to date!

Plugins:
  - snowflake: 1.5.0 - Up to date!
```

**The operating system you're using:**
Widnows 10
**The output of `python --version`:**
Python 3.8.13

### Are you interested in contributing the fix?

Sure, but definitely would need a hand getting started.

**Comment by anayds** [comment]
The [macro file](https://github.com/dbt-labs/dbt-codegen/blob/848c4b1f7b6ffd1873074a4b7e74c307f7a3533c/macros/generate_model_yaml.sql#L20) shows that the argument name in `generate_model_yaml` is actually `model_name` not `model_names`
(Alternately, you could skip explicitly stating the argument name to get results as-expected) 
This should be okay with a documentation fix?
