### ISSUE TITLE
Mint new release

### ISSUE THREAD

**Issue by ryantimjohn** [dbt-labs/dbt-codegen#128]
@joellabes I was wondering if y'all could mint a new release of dbt-codegen, there have been a ton of new features added in the last 6 months so I've had to run the main branch on most of my projects; would love to have a new release to run on my projects so I know it's stable. Thanks so much! (also, sorry to put this in as an issue, happy to put somewhere else if more appropriate!)

**Comment by joellabes** [comment]
Done, thanks!

**Comment by ryantimjohn** [comment]
Thank you!
