### ISSUE TITLE
Generate source does not work on External schema in Redshift

### ISSUE THREAD

**Issue by tsrp25** [dbt-labs/dbt-codegen#151]
### Describe the bug
Generate source macro does not work on External Schema tables in Redshift

### Steps to reproduce

I am trying to use the Generate source macro on the tables in external schema in Redshift. It is not generating any output.

### Expected results

Table metadata

### Actual results

Only below is created where stage is an external schema in redshift

sources:
  - name: stage
    description: ""
    tables:

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [X ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
DBT Cloud
```

**Comment by arindamsinhakeeper** [comment]
I am facing the same issue. codegen generate_source is not working on Redshift external schema

**Comment by mat-octave** [comment]
Me too. Using an external schema in Redshift. generate_source doesn't return any of the tables in the schema.

**Comment by arindamsinhakeeper** [comment]
Actually, I found out that it works for one table at a time, but not multiple tables.
