### ISSUE TITLE
dbt_project.yml version is not matching with the latest release version

### ISSUE THREAD

**Issue by yaseenhp** [dbt-labs/dbt-codegen#152]
### Describe the bug

dbt_project.yml version is not matching with the latest release version

### Steps to reproduce
Open dbt_project.yml and read **version** details.

### Expected results
I might be wrong, I expect the file to match the latest version 0.12.1

### Actual results

version: '0.12.1'

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by gwenwindflower** [comment]
Hi! Thank for your patience in getting this addressed, and thank you for flagging this. Will get this fixed right now.
