### ISSUE TITLE
Create a release for new features

### ISSUE THREAD

**Issue by pnadolny13** [dbt-labs/dbt-codegen#171]
Following https://github.com/dbt-labs/dbt-codegen/pull/168 merging it would be great to cut a release with the changes as @mickaelandrieu suggested in https://github.com/dbt-labs/dbt-codegen/pull/168#issuecomment-2030061769.

@gwenwindflower is that something you could help us with? 😄

**Comment by gwenwindflower** [comment]
@pnadolny13 we are planning to cut a release in the next week or two! fully agree we have a bunch of cool new stuff the past month or two, it's time!
