### ISSUE TITLE
Drop a new release please

### ISSUE THREAD

**Issue by ryantimjohn** [dbt-labs/dbt-codegen#187]
### Describe the bug

Several of the features in the documentation on Github aren't available unless you clone from Github. Y'all should drop a new release.

### Steps to reproduce

Try to use `case_sensitive_schemas` in a generate_source invocation:

`dbt run-operation generate_source --args '{"schema_name": "sample", "case_sensitive_schemas": "True", "case_sensitive_tables":"True"}'`

### Expected results

Case sensitive schemas!

### Actual results

```
Encountered an error while running operation: Compilation Error
  macro 'dbt_macro__generate_source' takes no keyword argument 'case_sensitive_schemas'
```

### System information

packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: dbt-labs/codegen
    version: 0.12.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

Versionless

**The operating system you're using:**

dbtCloud

**The output of `python --version`:**

dbtCloud

**Comment by dbeatty10** [comment]
@ryantimjohn we did a release earlier this week that includes the `case_sensitive_*` parameters for the `generate_source` macro (https://github.com/dbt-labs/dbt-codegen/pull/168):
- https://github.com/dbt-labs/dbt-codegen/releases/tag/0.13.0
- https://hub.getdbt.com/dbt-labs/codegen/0.13.0/
