### ISSUE TITLE
Snowflake - Shared Tables Do Not Appear In Information Schema

### ISSUE THREAD

**Issue by Nerdenberger** [dbt-labs/dbt-codegen#19]
Tables created in a DB via a snowflake table share do not appear in the information schema and so the source codegen doesn't work.  Still figuring out where they show up and how we can expand the initial table query to include them, but wanted to flag this here.

**Comment by clrcrl** [comment]
Oh that's so interesting! I use [dbt_utils.get_tables_by_prefix](https://github.com/fishtown-analytics/dbt-utils#get_relations_by_prefix)¹ to generate this list. We might have to update code there.

I just poked around an account that uses shares, and also couldn't find an information_schema that contained info about these tables!

¹Though this should be `get_relations_by_prefix`
