### ISSUE TITLE
Add ' description: "" ' to output from generate_source to match generate_model_yaml

### ISSUE THREAD

**Issue by BeantownData** [dbt-labs/dbt-codegen#28]
### Describe the feature
generate_model_yaml is great!   I like that it adds the description line even though it is blank.

I would love that same feature for generate_source.

### Describe alternatives you've considered
I could probably cobble something together with a script.

### Additional context
This would be especially powerful when combined with a script and yq to merge the yml files like I currently do.

### Who will this benefit?
Anyone who wants to document their data with as few a keystrokes as possible.

### Are you interested in contributing this feature?
At this time that isn't an option due to legal reasons.

Thanks!

**Comment by johnson-jay-l** [comment]
I think this exists now, see this file: macros/generate_source.sql

here's an example usage of the args that generate placeholder descriptions: `dbt run-operation generate_source --args '{"generate_columns": "True", "include_descriptions": "True", "schema_name": "some_schema", "database_name": "some_db"}'`
