### ISSUE TITLE
Duplicate packages in Hub DBT

### ISSUE THREAD

**Issue by mik-laj** [dbt-labs/dbt-codegen#46]
Currently, this library is available under two different names on the Hub:
- https://hub.getdbt.com/dbt-labs/codegen/latest/
- https://hub.getdbt.com/fishtown-analytics/codegen/latest/

The latest version is only available on ``dbt-labs/codegen``, but this package is not referenced in this repository. 
In particular, it would be useful to update the description of the repository:
![Screenshot 2021-07-19 at 06 36 20](https://user-images.githubusercontent.com/12058428/126103531-8dde1274-f94b-44c4-9f4c-d29cf6446e73.png)
And updating ``fishtown-analytics/codegen`` installation instructions to point to the new package.
![Screenshot 2021-07-19 at 06 36 50](https://user-images.githubusercontent.com/12058428/126103637-dc5adb06-7b72-4796-b4ff-87859f12660c.png)

**Comment by jtcohen6** [comment]
@mik-laj Good point, thanks for opening the issue! I've just updated the Hub site link in this repo, and I'll soon do the same for our other packages.

We're going to leave older versions of the packages in place, within the `fishtown-analytics` namespace, to avoid breaking changes for existing projects still referencing them there. We have switched all homepage links to `dbt-labs`, and we should do the same for any external links. I said a bit more about this in Discourse: https://discourse.getdbt.com/t/packages-dbt-labs-in-the-dbt-hub/2711/3

**Comment by mik-laj** [comment]
Why didn't you handle this transition in dbt 0.2.0?  It seems easy to add a warning that when there is a situation A, then you need to do step B.I understand this may not work all the time, but some of the checks can be done this way.

**Comment by mik-laj** [comment]
> Totally fair question. dbt doesn't know much about the packages it's installing, except what the package registry (dbt Hub) tells it—it passes the package name as organization/package, the Hub responds with which versions are available, it finds a version that satisfies all requirements.

I meant a much simpler solution.
```
packages_info = yaml.loads("packages.yml")
deprecated_packages = [p['package] for p in package_info.get('packages', []) if p['package].startswith('fishtown-analytics/')]
if deprecated_packages:
    warnings.warn("AA changed its name to BB. Please update BB to continue using this package. For details, see: https://discourse.getdbt.com/t/packages-dbt-labs-in-the-dbt-hub/2711", DeprecationWarning)
```
What do you think about adding a similar warning to dbt 0.20.1?  Do you think it can help migrate to newer versions and save users' time?
