### ISSUE TITLE
Use `print` instead of `log`

### ISSUE THREAD

**Issue by ehmartens** [dbt-labs/dbt-codegen#56]
### Describe the feature
Rather than using the `log` Jinja function to output generated code, use the `print` Jinja function added in [PR-4701](https://github.com/dbt-labs/dbt-core/pull/4701)

### Describe alternatives you've considered
Leave as-is.

### Additional context
This isue is based on a suggestion from @emmyoop ([here](https://github.com/dbt-labs/dbt-core/issues/3451#issuecomment-1031807152)) to allow for cleaner output from the macros using the new global `--quiet` flag in dbt. 

@jaypeedevlin and I worked on [PR-4701](https://github.com/dbt-labs/dbt-core/pull/4701) together to implement the solution she outlined in `dbt-core`, and would like to complete this next part of it as well.

### Who will this benefit?
Users who would like to copy the output from `dbt run-operation` directly into a file without having to remove info and warnings.

### Are you interested in contributing this feature?
Yep!

**Comment by pdfrod** [comment]
Can this be re-opened? As far as I can tell there's still no easy way to feed the output of `dbt run-operation` directly into a file without the logging noise.

**Comment by jaypeedevlin** [comment]
@pdfrod there's actually an open PR (linked above) which actions this which I'm trying to nudge towards a merge/release!
