### ISSUE TITLE
Macro Generate_Source is not working as expected for the generation of columns from BQ

### ISSUE THREAD

**Issue by swa-vuiben** [dbt-labs/dbt-codegen#57]
### Describe the bug

We are using the dbt-codegen Macros to help us in our work. Unfortunately, the "generate_source.sql" Macro is partially not working for some reason. The name of the source and the name of the table are retrieved normally, but the columns are not retrieved. We tried multiple way to take them, but it seems not possible. We are trying to fetch data from BQ and we put the parameters "generate_columns=True" and "include_descriptions=True".

### Steps to reproduce

We are using the following command to trigger the launch of the Macro and then the output is given without columns :
dbt run-operation generate_source --args '{schema_name: tiktok_ads}'

### Expected results
We were expecting to receive the list of columns that are provided in BQ

### Actual results
The list of columns is empty ; no columns names are listed

### Screenshots and log output
![image](https://user-images.githubusercontent.com/77483021/154726588-292c94c6-2870-4bd2-902c-52c38831e02d.png)

### System information
packages:
  - package: dbt-labs/codegen
    version: 0.4.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
installed version: 0.21.0
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.21.0
  - redshift: 0.21.0
  - bigquery: 0.21.0
  - snowflake: 0.21.0

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.8.11

### Additional context

Our hypothesis is that the problem comes from this part of the code, but we are unsure, could you please assist us in the resolution, please ?

![image](https://user-images.githubusercontent.com/77483021/154729058-60f5f510-f05c-41b8-b436-8ee3d2efdc31.png)

### Are you interested in contributing the fix?

We are at your disposal for any further information or help in order to achieve the resolution of this problem on our side.

**Comment by djayatillake** [comment]
Have you tried using the dbt Cloud IDE scratchpad?

I just used it now for one schema of mine and I don't get the same result, the columns come back just fine:
{{ codegen.generate_source('streamkap', generate_columns=True, include_descriptions=True) }}
