### ISSUE TITLE
Optional table_pattern on generate_source.sql

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-codegen#59]
### Describe the feature
Add a parameter to the generate_source macro which exposes the `table_pattern` parameter used in `dbt_utils.get_relations_by_pattern`. 

Here is a starter implementation of the idea:

```
{% macro get_tables_in_schema(schema_name, database_name=target.database, table_pattern='') %}
    
    {% if table_pattern != '' %}
        {% set tables=dbt_utils.get_relations_by_pattern(
            database=database_name,
            schema_pattern=schema_name,
            table_pattern=table_pattern
        ) %}
    {% else %}
        {% set tables=dbt_utils.get_relations_by_pattern(
            database=database_name,
            schema_pattern=schema_name,
            table_pattern='%'
        ) %}

    {% endif %}

    {% set table_list= tables | map(attribute='identifier') %}

    {{ return(table_list | sort) }}

{% endmacro %}
```

### Describe alternatives you've considered
- Individual users could modify their own macros to override the default behavior
- Users can parse larger yamls after the fact to target the sources they ultimately want to map
- Users could move data from existing schemas to new "dbt specific" raw schemas and then use codegen against those. This option somewhat defeats a benefit of codegen in getting new users up-and-running quickly with dbt.

### Additional context
Relevant for all databases

### Who will this benefit?
Users with raw data schemas that contain *more* tables than they want to map into their dbt projects. 

### Are you interested in contributing this feature?
Sure - I have a branch sitting locally that I can push up if we have alignment.

**Comment by joellabes** [comment]
Yeah I buy it! 

I imagine that instead of checking for an empty string in table pattern, you could set the default value to `'%'` right? 

```
{% macro get_tables_in_schema(schema_name, database_name=target.database, table_pattern='%') %}
```

**Comment by matt-winkler** [comment]
@joellabes yeah good call - this is what happens when you code on a Friday afternoon :). I'll add a new PR and we can take it from there.

**Comment by matt-winkler** [comment]
This is addressed by https://github.com/dbt-labs/dbt-codegen/pull/60
