### ISSUE TITLE
Support for external tables (databricks)

### ISSUE THREAD

**Issue by lassebenni** [dbt-labs/dbt-codegen#62]
Hi, I really like this package! Unfortunately it doesn't seem to support creating a source from external tables (e.g. Databricks Lakehouse). 

I looked at the [generate_source.sql](https://github.com/dbt-labs/dbt-codegen/blob/main/macros/generate_source.sql)` code, which calls [dbt_utils.get_relations_by_pattern](https://github.com/dbt-labs/dbt-utils/blob/main/macros/sql/get_relations_by_pattern.sql) to create a list of tables. Unfortunately that only seems to work for relational databases(?). We are using the [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) package to create our external (hive) tables, but it requires manually putting in all the source information and this package would be very helpful.

Do you think it would be a lot of work to make it work for external tables?

**Comment by Olaktal** [comment]
+1 for Redshift Spectrum external tables 🙏

**Comment by bencmbrook** [comment]
Commenting to reopen... this would be so valuable (+1 on Redshift Spectrum)

**Comment by RobertDCI** [comment]
+1 for databricks. This would be great
