### ISSUE TITLE
Write to file

### ISSUE THREAD

**Issue by Trymzet** [dbt-labs/dbt-codegen#71]
For anyone looking, for example for the `generate_source` macro, in order to write to file you can change line 77 in `generate_source.sql` (`{{ log(joined, info=True) }}`) to `{{ print(joined) }}` and then run:

`dbt -q run-operation your_codegen_operation > file.yaml`

**Comment by jaypeedevlin** [comment]
This is a dupe of https://github.com/dbt-labs/dbt-codegen/issues/56

**Comment by Trymzet** [comment]
Yes but the other issue is very hard to find as its name is taken from the solution and not from the problem, so I just wanted to put this one here so the solution is easily discoverable.
