### ISSUE TITLE
[CT-1605] [Bug] generate_source sometimes fails without explanation

### ISSUE THREAD

**Issue by jaredx435k2d0** [dbt-labs/dbt-codegen#95]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If I run
`dbt run-operation generate_source --args '{"schema_name": "my_schema_name", "database_name": "my_db_name"}'`

The output will sometimes be:
```

version: 2

sources:
  - name: my_schema_name
    database: my_db_name
    tables:
```

Other times, it works great.

### Expected Behavior

I would expect a full sources document to be created, with each table, always.

### Steps To Reproduce

It consistently happens with the same schemas, but I'm not sure why.
Run
`dbt run-operation generate_source --args '{"schema_name": "my_schema_name", "database_name": "my_db_name"}'`
See that output never gets to the first table.

Both schemas for which I'm currently seeing this problem are populated via Fivetran's Google Sheets connector, and have `_ROW` as their first column

Still, I have other schemas populated by the same connector (in the same DB), with tables that have the same first column name, that work great with this command.

### Relevant log output

```shell
I don't see any logs for this, nor error messages.
```

### Environment

```markdown
- OS: macOS 12.6.1 (21G217)
- Python: Python 3.10.7
- dbt-core:
- dbt-snowflake: 1.3.0
```

**Comment by boblannon-fp** [comment]
this looks related to my issue, i think... under "additional context" I included my findings.  It seems to have to do with the fact that snowflake returns column names in all-caps. 

https://github.com/dbt-labs/dbt-codegen/issues/82
